import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { createRequire } from 'node:module';
const { chromium } = createRequire(import.meta.url)('playwright');
const base = process.env.PANEL_QA_URL || 'http://127.0.0.1:5197';
assert.ok(['127.0.0.1', 'localhost'].includes(new URL(base).hostname));
const output = process.env.PANEL_QA_OUTPUT || path.resolve('../output/jornada-aplicada-20260910');
await fs.mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true, channel: process.env.PANEL_QA_BROWSER || 'chrome' });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, timezoneId: 'America/Mexico_City' });
await context.route('**/*', r => ['127.0.0.1', 'localhost'].includes(new URL(r.request().url()).hostname) ? r.continue() : r.abort());
const page = await context.newPage();
const pruebas = [], errores = [];
page.on('pageerror', e => errores.push(e.message));
page.on('dialog', d => d.accept());
const check = (name, value) => { assert.ok(value, name); pruebas.push(name); };
const nav = async name => { await page.getByRole('navigation', { name: 'Consultorio', exact: true }).getByRole('button', { name, exact: true }).click(); await page.locator('.resp-cab h1').waitFor(); };
const ready = () => page.getByRole('button', { name: 'Actualizar datos' }).waitFor({ state: 'visible' });
const abrirNombre = name => page.locator('.jornada-nombre').filter({ hasText: name }).first().click();
const casoListo = () => page.getByRole('tab', { name: 'Resumen', exact: true }).waitFor();
try {
  await page.goto(base + '/tests/panel-fixture.html');
  await page.getByRole('button', { name: 'Abrir panel con datos ficticios' }).click();
  await ready();
  await page.locator('.jornada-table tbody tr').first().waitFor();
  check('Una fila por cita, no por envio', await page.locator('.jornada-table tbody tr').count() === 6);
  const tiempos = await page.locator('.jornada-hora').allTextContents();
  check('Horario ascendente', tiempos[0].includes('08:00') && tiempos[5].includes('10:30'));
  check('No hay paciente seleccionada automaticamente', await page.locator('.consulta-head').count() === 0);
  check('No hay catalogo global de calculadoras', await page.getByRole('button', { name: 'Valoración activa', exact: true }).count() === 0);
  check('No se presenta manifiesto como archivo disponible', await page.getByText('Disponibilidad por comprobar').isVisible());
  await page.screenshot({ path: path.join(output, 'jornada-desktop.png'), fullPage: true });
  await abrirNombre('Álvarez'); await casoListo();
  check('Contexto unico de paciente', await page.locator('.consulta-head h1').innerText() === 'Paciente de prueba · Álvarez');
  check('MRS incompleta no se transforma en negativa', (await page.locator('.resp-summary').innerText()).includes('Escala MRS incompleta'));
  check('Sin intensidad no es cero', !(await page.locator('.resp-summary').innerText()).includes('0 de 10'));
  check('Campos clinicos preservados', (await page.locator('.resp-summary').innerText()).includes('Penicilina'));
  await page.getByRole('tab', { name: 'Respuestas', exact: true }).click();
  check('Dato legacy no desaparece', (await page.getByRole('tabpanel', { name: 'Respuestas', exact: true }).innerText()).includes('Conservar también el dato histórico.'));
  await page.getByRole('tab', { name: 'Historial', exact: true }).click();
  check('Dos envios bajo identidad confirmada', await page.locator('.consulta-history li').count() === 2);
  await page.getByRole('tab', { name: 'Resumen', exact: true }).click();
  await page.getByRole('button', { name: 'Marcar preconsulta revisada' }).click();
  await page.getByRole('button', { name: 'Reabrir revisión' }).waitFor();
  check('Revision explicitamente guardada', await page.getByText('Guardado solo en este equipo', { exact: true }).isVisible());
  await page.reload(); await page.locator('.jornada-table tbody tr').first().waitFor();
  check('Revision persiste al recargar', (await page.locator('.jornada-table tbody tr').first().innerText()).includes('Revisada'));
  await abrirNombre('Álvarez'); await casoListo();
  await page.getByRole('button', { name: 'Reabrir revisión' }).click();
  await page.getByRole('button', { name: 'Marcar preconsulta revisada' }).waitFor();
  await page.getByRole('tab', { name: 'Valoración', exact: true }).click();
  check('No hay 0 de 10 ni diez tarjetas vacias', await page.locator('.rp-card').count() === 0);
  await page.getByLabel('Agregar instrumento', { exact: true }).selectOption('hemorragia');
  await page.getByRole('button', { name: 'Agregar instrumento seleccionado' }).click();
  await page.getByRole('heading', { name: 'Selección médica · 1' }).waitFor();
  await page.getByRole('button', { name: 'Evaluar', exact: true }).click();
  await page.locator('.consulta-instrumento .inst').waitFor();
  check('Calculadora abre dentro de la misma paciente', await page.locator('.consulta-head h1').innerText() === 'Paciente de prueba · Álvarez');
  await page.screenshot({ path: path.join(output, 'instrumento-desktop.png'), fullPage: true });
  await page.getByRole('button', { name: 'Volver a la selección y resultados' }).click();
  check('Seleccion conservada tras calculadora', await page.getByRole('heading', { name: 'Selección médica · 1' }).isVisible());
  await page.getByRole('button', { name: 'Retirar Hemorragia uterina anormal', exact: true }).click();
  await page.getByRole('heading', { name: 'Selección médica · 0' }).waitFor();
  check('Quitar no obliga a usar instrumentos sugeridos', true);
  await nav('Jornada'); await abrirNombre('Benítez');
  await page.getByRole('heading', { name: 'Sin preconsulta confirmada para esta cita' }).waitFor();
  check('Coincidencia de telefono no es identidad confirmada', await page.getByText('Coincidencia', { exact: false }).count() > 0);
  await page.locator('.consulta-candidatas').getByRole('button', { name: 'Revisar', exact: true }).first().click(); await casoListo();
  check('Confirmacion no se ejecuta sin control medico', await page.getByRole('button', { name: 'Confirmar asociación' }).isDisabled());
  await page.getByRole('checkbox', { name: 'Confirmé que esta paciente', exact: false }).check();
  await page.getByRole('button', { name: 'Confirmar asociación' }).click();
  await page.getByText('Cita vinculada · identidad confirmada en el panel').waitFor();
  await page.getByRole('button', { name: 'Marcar preconsulta revisada' }).waitFor();
  check('Vincular no equivale a revisar', true);
  await page.locator('.consulta-vinculo-confirmado summary').click();
  await page.getByRole('button', { name: 'Retirar asociación', exact: true }).click();
  await page.getByRole('button', { name: 'Confirmar asociación', exact: true }).waitFor();
  check('Retirar exige nueva confirmacion', await page.getByRole('button', { name: 'Confirmar asociación' }).isDisabled());
  check('Identidad retirada no queda seleccionada invisible', await page.getByLabel('Identidad de la paciente', { exact: true }).inputValue() === 'nueva');
  await page.getByRole('checkbox', { name: 'Confirmé que esta paciente', exact: false }).check();
  await page.getByRole('button', { name: 'Confirmar asociación' }).click();
  await page.getByText('Cita vinculada · identidad confirmada en el panel').waitFor();
  await nav('Pacientes');
  check('Identidades agrupadas sin duplicar historial', await page.locator('.jornada-pacientes tbody tr').count() === 4);
  await nav('Por revisar');
  await page.getByRole('searchbox', { name: 'Buscar paciente, teléfono o motivo' }).fill('benitez');
  check('Busqueda sin acentos en todas las respuestas', await page.locator('.jornada-table tbody tr').count() === 1);
  await abrirNombre('Benítez'); await casoListo();
  await page.getByRole('tab', { name: 'Resumen', exact: true }).focus();
  await page.keyboard.press('End');
  check('Navegacion de tabs por teclado', await page.getByRole('tab', { name: 'Historial', exact: true }).getAttribute('aria-selected') === 'true');
  await page.getByRole('button', { name: 'Volver a pendientes' }).click();
  check('Volver conserva busqueda', await page.getByRole('searchbox', { name: 'Buscar paciente, teléfono o motivo' }).inputValue() === 'benitez');
  await page.getByRole('searchbox', { name: 'Buscar paciente, teléfono o motivo' }).fill('');
  check('Paginacion evita omitir listado grande', await page.getByRole('button', { name: 'Mostrar 25 más por grupo' }).isVisible());
  await page.getByRole('button', { name: 'Mostrar 25 más por grupo' }).click();
  check('Cargar mas incluye todos los pendientes', await page.locator('.jornada-table tbody tr').count() === 33);
  await nav('Jornada');
  await page.getByLabel('Fecha de la jornada').fill('2020-01-01');
  await page.getByText('No hay citas en esta prueba local.').waitFor();
  check('Un dia vacio no muestra todos los cuestionarios', await page.locator('.jornada-table tbody tr').count() === 0);
  await page.getByRole('button', { name: 'Hoy', exact: true }).click();
  await page.locator('.jornada-table tbody tr').first().waitFor();
  for (const width of [320, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 950 });
    await nav('Jornada');
    check('Jornada sin desbordamiento ' + width, await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
    await page.screenshot({ path: path.join(output, 'jornada-' + width + '.png'), fullPage: true });
    await abrirNombre('Álvarez'); await casoListo();
    for (const tab of ['Resumen', 'Respuestas', 'Estudios', 'Valoración', 'Historial']) {
      await page.getByRole('tab', { name: tab, exact: true }).click();
      check(tab + ' sin desbordamiento ' + width, await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
    }
    await page.getByRole('tab', { name: 'Resumen', exact: true }).click();
    await page.screenshot({ path: path.join(output, 'consulta-' + width + '.png'), fullPage: true });
  }
  await page.emulateMedia({ media: 'print' });
  check('Impresion contiene solo la paciente abierta', await page.locator('.consulta-head h1').isVisible() && await page.locator('.resp-summary').isVisible() && !(await page.locator('.consultorio-chrome').isVisible()));
  await page.emulateMedia({ media: 'screen' });
  check('Sin errores JS', errores.length === 0);
  await fs.writeFile(path.join(output, 'browser-qa.json'), JSON.stringify({ pruebas, errores, alcance: 'Datos ficticios en almacenamiento local, sin servicios reales.' }, null, 2));
  console.log(JSON.stringify({ comprobaciones: pruebas.length, errores }));
} catch (e) {
  await page.screenshot({ path: path.join(output, 'fallo-jornada.png'), fullPage: true });
  console.error(JSON.stringify({ pruebas, errores, fallo: e.message }, null, 2)); throw e;
} finally { await browser.close(); }
