import assert from 'node:assert/strict';
import { reporteClinico as r } from './precarga-clinica-fixtures.mjs';
import { pacienteDesdeRespuesta } from '../core/precarga.js';
import { precargaInstrumento, combinarPrecarga, numeroClinico } from '../core/precargaClinica.js';
import { evaluarMrs, MRS_ITEMS } from '../instruments/menopausia/engine.js';
import { evaluarSeveridad } from '../instruments/incontinencia/engine.js';
import { condicionesAutomaticas } from '../instruments/anticoncepcion/engine.js';
import { instrumentosPara } from '../core/ruteoClinico.js';
import { evaluarProfundizacion, MODULOS } from '../core/profundos/index.js';
import { validarEntrevista } from '../core/entrevista.js';
import { AREAS_CLINICAS } from '../core/areasClinicas.js';
let n = 0;
const eq = (a, b, msg) => { assert.deepEqual(a, b, msg); n++; };
const p = pacienteDesdeRespuesta(r), snapshot = JSON.stringify(r);
const get = id => precargaInstrumento(id, p);
eq(get('hemorragia').valores.duracionDias, 9);
eq(get('hemorragia').valores.frecuenciaDias, 40);
eq(get('hemorragia').valores.regular, false);
eq(get('hemorragia').valores.coag_dental, true);
eq(get('hemorragia').valores.contexto, undefined, 'Edad no establece menopausia');
eq(get('sop').valores.longitudCiclo, 40);
eq(get('sop').valores.menosDeOchoPorAnio, true);
eq(get('sop').valores.cualquierCicloMayor90, false);
eq(get('sop').valores.hiperandrogenismo, undefined);
eq(get('dolor-pelvico').valores.intensidadEVA, 6);
eq(get('dolor-pelvico').valores.duracionMeses, 8);
eq(get('dolor-pelvico').valores.patron, 'ciclico');
eq(get('endometriosis').valores.dispareunia, true);
eq(get('endometriosis').valores.dischezia, true);
eq(get('endometriosis').valores.objetivoFertilidad, false);
eq(get('incontinencia').valores.cantidadPerdida, 2, '4 puntos de cantidad equivalen a índice 2, no índice 4');
eq(get('incontinencia').valores.nicturia, 0);
eq(evaluarSeveridad(get('incontinencia').valores).puntaje, 13);
eq(evaluarSeveridad({ frecuenciaPerdida: null, cantidadPerdida: null, impactoVida: null }), null);
eq(get('mama').valores.familiarMamaMenor50, true);
eq(get('mama').valores.familiarMama2oMas, false);
eq(get('mama').valores.mutacionConocida, undefined, 'No sé no significa negativo');
eq(get('osea').valores.fracturaFragilidad, true);
eq(get('osea').valores.glucocorticoides, undefined, 'Sin dosis no se importa criterio FRAX');
eq(get('anticoncepcion').valores.fumaIntenso, true);
eq(get('anticoncepcion').valores.condiciones.migranaAura, true);
eq(p.antecedentes.estatina, false);
eq(p.antecedentes.antihipertensivo, true);
eq(get('cardiometabolico').compartidos.some(f => f.destino === 'antecedentes.diabetes'), true);
eq(p.labs, undefined); eq(p.signos, undefined);
eq(get('menopausia').campos.filter(f => f.destino.startsWith('mrs_')).length, 11);
eq(evaluarMrs(get('menopausia').valores).completo, true);
for (const x of [undefined, null, '', ' ', false, true, NaN, Infinity, -1]) eq(numeroClinico(x), null);
const mrs = Object.fromEntries(MRS_ITEMS.map(i => [i.id, 0]));
eq(evaluarMrs(mrs).total, 0);
for (const v of [undefined, null, '', false, -1, 5, 1.2, '2']) eq(evaluarMrs({...mrs, mrs_bochornos:v}).total, null);
eq(combinarPrecarga({a:1, c:{x:true}}, {a:2,b:3,c:{y:true}}, {a:null,b:0,c:{x:false}}), {a:null,b:0,c:{x:false,y:true}});
eq(precargaInstrumento('mama', {}).campos.length, 0);
eq(JSON.stringify(r), snapshot, 'No modifica respuestas recibidas');
eq(get('mama').campos.every(f => f.fuente.startsWith('autoReporte.')), true);
eq(condicionesAutomaticas({demografia:{edad:46},signos:{}}, {fuma:true,fumaIntenso:null}).tabaco35menos, undefined);
eq(instrumentosPara({autoReporte:{hc:{temasConsulta:['osea']}}}).instrumentosSugeridos.some(s=>s.instrumento==='osea'), true);
eq(instrumentosPara({autoReporte:{hc:{fracturaBajoImpacto:true}}}).instrumentosSugeridos.find(s=>s.instrumento==='osea').prioridad, 'alta');
for (const m of MODULOS) {
  eq(evaluarProfundizacion(m.ID, {}).completo, false, m.ID + ' vacío no es completo');
  eq(evaluarProfundizacion(m.ID, Object.fromEntries(m.PREGUNTAS.map(q=>[q.id,null]))).completo, false);
}
const sex = evaluarProfundizacion('salud-sexual',{ss_deseo:1,ss_excitacion:0,ss_lubricacion:0,ss_orgasmo:0,ss_satisfaccion:5,ss_dolor:0});
eq(sex.positivo, null); eq(sex.total, null); eq(sex.validado, false);
eq(validarEntrevista('osea',{caidasUltimoAnio:0}).ok, true);
eq(validarEntrevista('osea',{caidasUltimoAnio:-1}).ok, false);
eq(validarEntrevista('osea',{fracturaBajoImpacto:'no_se'}).ok, true);
eq(validarEntrevista('osea',{}).ok, true);
eq(validarEntrevista('sangrado',{sangradoOtrosSitios:['ninguna','dental']}).ok, false);
const lum = h => { const a = h.slice(1).match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4); return a[0]*.2126+a[1]*.7152+a[2]*.0722; };
for (const area of Object.values(AREAS_CLINICAS)) eq((lum(area.fondo)+.05)/(lum(area.color)+.05)>=4.5, true, 'Contraste texto/fondo '+area.nombre);
console.log(`Precarga clínica y semántica: ${n} comprobaciones correctas; solo datos ficticios.`);
